from __future__ import annotations

GLOBAL_STOP_WORDS = {
    "and", "the", "with", "for", "from", "that", "this", "will", "are", "you", "your", "our", "have", "has",
    "into", "about", "job", "role", "candidate", "candidates", "requirements", "requirement", "required", "including",
    "preferred", "qualification", "qualifications", "ability", "abilities", "responsibilities", "responsibility",
}

GLOBAL_WEAK_TOKENS = {
    "experience", "skills", "team", "work", "working", "help", "plus", "years", "year",
    "modern", "feature", "features", "tool", "tools", "quick", "strong", "solid", "ideal", "ideally", "familiar",
    "comfortable", "proficient", "high", "fast", "pace", "paced", "note", "final", "right",
    "benefits", "compensation", "salary", "full-time", "schedule", "location",
    "travel", "in person", "weekly pay", "mileage", "reimbursement",
    "data", "company", "paid", "employee", "work",
    "step", "candidate", "required", "engineer", "fullstack", "applications", "communication", "contributor", "end",
    "support", "developer", "business", "onboarding", "note",
    # Important in context, weak by default rather than hard-stop.
    "design", "production", "system", "systems", "strategy", "build", "built", "building",
    # Common generic business/resume language that should rarely outrank concrete terms.
    "manager", "management", "lead", "service", "platform", "engineering", "business",
    "performance", "delivery", "execution", "opportunities", "create", "developing",
    "defined", "related", "assistant", "area", "needs",
    "ensure", "through", "teams", "clients", "ownership", "all", "daily", "using",
    "software", "flow", "hiring", "join", "make", "customer",
    "can", "information", "another", "top", "care", "clear", "comprehensive",
    "eligible", "employment", "privacy", "recruiting", "supported", "projects",
    "during", "functions", "environment", "degree", "must", "perform", "across", "analyses",
    "choose", "their", "based", "career", "open", "position", "who", "any", "able", "providing", "ensures", "receive", "requires",
    "university", "campus", "location",
    "graduates", "graduate", "students", "recent",
    "may", "needed", "knowledge", "duties", "custom", "effectively", "familiarity", "mission",
}
GLOBAL_GARBAGE_TOKENS = {"etc", "etcetera", "misc", "various", "eg", "e.g"}

GLOBAL_FILLER_PHRASES = {
    "team player", "move fast", "strong communication skills", "excellent communication skills", "high standards",
    "seat at the table", "works well under pressure", "self starter", "detail oriented",
    "customer first", "integrity", "collaborative", "innovative", "passionate", "best in class",
    "unparalleled customer service", "vacation time", "sick time", "holiday pay",
    "healthcare benefits", "401k", "tuition reimbursement", "self-motivated", "skilled and motivated",
    "communicates effectively", "nimble learning", "functional skills", "situational adaptability",
    "our mission is clear and simple", "change agents", "improve their lives and livelihood",
    "send us your resume for consideration", "integral part of the continued growth of our organization",
    "women and minorities are encouraged to apply", "equal employment opportunity company", "drug free work place",
    "competitive compensation package", "passion confidence and tenacity",
    "inclusive environment", "inclusive work environment", "open-door policy", "ready to work hard",
    "proven strategies", "ideal customer", "impeccable track record", "incredible team", "hands-on training",
    "additional benefits and pay will be further discussed", "driven ambitious", "team building activities",
    "friends and family nights", "sense of humor", "active lifestyle", "socially aware",
    "act with uncompromising integrity", "provide outstanding service", "build trusted relationships",
    "drive innovation", "work in partnership", "personally accountable", "respect and dignity",
    "we value your well-being", "we value your time", "we value your development", "we value your perspective",
    "we value our communities", "equal opportunity employer", "not sure if you meet every requirement",
    "company paid", "business casual dress code", "community outreach opportunities",
    "employee recognition programs", "holiday bonus", "hybrid work",
    "pay range is the lowest to highest compensation", "all qualified applicants will receive consideration",
    "by clicking apply today you agree to receive calls", "message and data rates may apply",
    "carriers are not liable for delayed or undelivered messages", "you will always have the right to cease communicating",
    "talk to recruiter", "recruiter network", "who are our recruiters", "we never post fake jobs",
    "next steps", "dream job", "for free", "apply now", "apply today",
    "public trust clearance", "us citizenship or perm resident alien status", "background records check",
    "remote work from home", "continental united states of america",
}

GLOBAL_PHRASES = [
    "stakeholder management", "cross functional collaboration", "end-to-end ownership", "process improvement", "risk mitigation",
    "incident response", "root cause analysis", "data analysis", "business impact", "customer outcomes", "go to market",
    "a/b testing", "ab testing", "user acquisition", "user activation", "user retention",
    "operational performance", "consistent execution", "drive accountability", "workforce planning", "revenue performance",
    "operational inefficiencies", "performance standards", "professional services",
    "business development", "account management", "lead generation", "outbound prospecting", "sales engagement",
    "revenue growth", "new business opportunities", "revenue-focused pipeline", "client activity", "recurring volume",
    "relationship-building", "client experience", "pipeline health", "performance metrics", "market trends",
    "competitive developments", "prospecting strategies", "sales process", "activity tracking",
    "business management", "business ownership", "cash flow forecasting", "profit loss statements", "profit and loss statements",
    "organizational turnaround", "operational turnaround", "financially measurable results", "managing teams",
    "face-to-face interaction", "sales presentations", "customer service", "training and development", "sales operations",
    "forward deployed software engineer", "customer-facing engineering", "customer solution delivery", "technical lead",
    "platform customization", "embedded platform", "application-layer enhancements", "developer relations",
    "requirement gathering", "architecture reviews", "developer support", "platform capabilities",
    "business goals", "application-layer components", "service extensions", "rest-based apis", "systems integration",
    "api design", "interface design documents", "technical troubleshooting", "root-cause analysis",
    "technical escalation support", "customer-specific development", "technical direction", "embedded systems",
    "integration workflows", "partner tools",
    "data pipelines", "sql optimization", "complex query design", "kafka streaming", "connector development",
    "databricks workflow development", "medallion architecture", "data governance", "performance tuning",
    "data security", "privacy best practices", "ml pipelines", "training deployment monitoring",
    "data architectures", "ml workloads", "llm-based solutions", "rag architectures", "generative ai",
    "data integration",
    "intelligent workflow automation", "internal process enhancements", "internal workflows", "workflow automation",
    "automation governance", "governance models", "process automation", "operational efficiency",
    "monitoring solutions", "performance tracking", "api integration", "cloud-deployed scripts",
    "automation strategies", "dashboarding", "documentation skills",
    "full-stack features", "next.js", "react native", "end-to-end delivery", "customer discovery",
    "technical architecture", "development velocity", "ai dev tooling", "ci/cd", "production-grade web applications",
    "product-minded", "deployment and maintenance", "financial infrastructure", "modern accounting", "banking tools",
    "fintech", "b2b saas",
    "full stack engineer", "end-to-end", "microservices", "individual contributor", "multiple applications",
    "vue", "nextjs", "nestjs", "php", "linux", "restful apis", "third-party apis",
    "full stack web development", "javascript frameworks", "github", "notion",
    "quantitative investment", "investment decision-making", "data analytics platform", "business requirements",
    "development specifications", "working prototypes", "data modeling", "structured and unstructured data",
    "quantitative research", "business intelligence", "tableau", "private markets", "investment management",
    "model creation", "machine learning model development", "feature engineering", "model optimization",
    "domain appropriate metrics", "model performance evaluation", "event-driven microservices", "graphql",
    "mcp servers", "ai-powered applications", "cloud on-premises deployment", "mlops best practices",
    "data preprocessing", "deep learning models", "high throughput services", "fraud prevention",
    "loss prevention", "parcel delivery optimization",
    "speech analytics", "sentiment analytics", "intent models", "dialog flows", "self-service automation",
    "ivr improvements", "agent assist", "cx analytics", "automation workflows", "customer satisfaction",
    "containment rate", "escalation rate", "contact center", "cisco webex contact center", "calabrio one",
    "patient care", "appointment scheduling", "medical records", "clinical documentation", "care coordination",
    "classroom instruction", "lesson planning", "curriculum development", "student assessment", "behavior management",
    "legal documentation", "case management", "document review", "court filings", "docket management",
    "construction materials testing", "field testing", "site inspection", "quality control", "safety compliance",
    "sales engineering", "solution selling", "technical demos", "pre-sales support", "support operations",
    "service desk support", "incident triage", "ticket resolution", "business systems analysis", "requirements analysis",
]

GLOBAL_BOOST_WORDS = {
    "stakeholder management": 3, "cross functional collaboration": 2, "end-to-end ownership": 3, "process improvement": 3,
    "risk mitigation": 3, "incident response": 3, "root cause analysis": 3, "data analysis": 3, "business impact": 3,
    "customer outcomes": 2, "go to market": 2, "a/b testing": 3, "user acquisition": 3, "user activation": 3, "user retention": 3,
    "operations": 3, "ownership": 3, "accountability": 3, "execution": 3, "revenue": 3, "collections": 3, "billing": 3,
    "kpis": 3, "dashboards": 2, "hiring": 2, "recruiting": 2, "performance": 3, "operator": 2, "efficiency": 2, "implementation": 2,
    "sales": 3, "pipeline": 3, "prospecting": 3, "outbound": 2, "lead": 2, "leads": 2, "crm": 3,
    "forecasting": 2, "reporting": 2, "clients": 2, "client": 2, "account": 2, "relationships": 2, "relationship": 2,
    "onboarding": 2, "metrics": 2, "targets": 2, "opportunities": 2, "volume": 2, "compliance": 2, "product": 1,
    "budgeting": 3, "profit": 3, "cash": 2, "flow": 2, "excel": 2, "management": 2, "turnaround": 3,
    "productivity": 2, "forecasting": 3, "sales": 3, "marketing": 2, "customer": 1, "service": 1, "training": 1, "leadership": 1,
    "python": 3, "django": 3, "react": 3, "aws": 3, "apis": 3, "api": 3, "integration": 3, "integrations": 3,
    "embedded": 3, "platform": 2, "partners": 2, "developer": 2, "architecture": 2, "sdk": 2, "microservices": 2,
    "troubleshooting": 2, "support": 2, "deployment": 2, "delivery": 2, "customization": 2,
    "sql": 3, "kafka": 3, "databricks": 3, "nifi": 3, "druid": 2, "mongodb": 2, "opensearch": 2, "postgres": 2,
    "governance": 2, "security": 2, "privacy": 2, "mlops": 3, "rag": 3, "llm": 3, "generative": 2,
    "pipelines": 2, "architecture": 2, "monitoring": 2, "streaming": 2,
    "automation": 3, "copilot": 3, "power automate": 3, "power bi": 2, "dataverse": 3, "scripting": 3,
    "kpi": 2, "kpis": 3, "dashboarding": 2, "workflow": 2, "prompt engineering": 2, "documentation": 2,
    "typescript": 3, "next.js": 3, "react native": 3, "full-stack": 3, "deployment": 2, "maintenance": 2,
    "fintech": 2, "banking": 2, "accounting": 2, "ci/cd": 2, "customers": 1,
    "gcp": 3, "gke": 3, "docker": 3, "kubernetes": 3,
    "vue": 3, "nextjs": 3, "nestjs": 3, "php": 3, "linux": 2,
    "restful apis": 3, "third-party apis": 3, "full stack web development": 3, "javascript frameworks": 2,
    "github": 2, "notion": 1,
    "tableau": 3, "power bi": 3, "business intelligence": 3, "data modeling": 3, "quantitative": 3,
    "investment": 3, "private markets": 3, "investment management": 3, "analytics platform": 3, "prototypes": 2,
    "numpy": 3, "pandas": 3, "scikit-learn": 3, "tensorflow": 3, "pytorch": 3, "transformers": 3,
    "fastapi": 3, "flask": 2, "django": 3, "angular": 2, "vue.js": 2, "graphql": 3,
    "redis": 2, "postgresql": 2, "mysql": 2, "azure": 2, "mlops": 3, "feature engineering": 3,
    "model optimization": 3, "data preprocessing": 2, "deep learning": 3, "microservices": 3,
    "webex": 3, "calabrio": 3, "ivr": 3, "fcr": 3, "csat": 3, "dialogflow": 3, "cx": 2, "wfo": 2, "ccaas": 2, "wxcc": 2,
}

GLOBAL_PHRASE_CANONICAL = {
    "ab testing": "a/b testing",
    "end to end ownership": "end-to-end ownership",
    "daily operations": "day-to-day operations",
    "sdr": "sales development",
    "bdr": "business development",
    "crm platforms": "crm",
    "sales engagement tools": "sales engagement",
    "performance metrics": "metrics",
    "profit & loss statements": "profit loss statements",
    "profit and loss statements": "profit loss statements",
    "p&l": "profit loss statements",
    "rest-based apis": "api design",
    "apis": "api",
    "integrations": "integration",
    "root cause analysis": "root-cause analysis",
    "interface design documents": "interface documentation",
    "idds": "interface documentation",
    "llm based solutions": "llm-based solutions",
    "powerautomate": "power automate",
    "microsoft copilot": "copilot",
    "fullstack engineer": "full stack engineer",
    "full stack": "full stack engineer",
    "end to end": "end-to-end",
    "nextjs": "next.js",
    "rest api": "restful apis",
    "rest apis": "restful apis",
    "third party apis": "third-party apis",
    "bi": "business intelligence",
    "scikit learn": "scikit-learn",
    "ml ops": "mlops",
    "ai ml": "machine learning model development",
    "vue js": "vue.js",
    "cloud/on-premises": "cloud on-premises deployment",
    "cross-functional teams": "cross functional collaboration",
    "architectural discussions": "technical architecture",
    "user facing web applications": "user-facing web applications",
}
GLOBAL_ALLOW_SHORT_TOKENS = {"c++", "c#", "go", "r", "ai", "ml", "ui", "ux", "qa", "cx", "ivr", "fcr", "csat", "wfo", "ccaas", "wxcc"}

DOMAIN_LEXICONS = {
    "engineering": {
        "aliases": {
            "engineer", "engineering", "developer", "software", "frontend", "backend", "full stack", "platform",
            "forward deployed", "software engineer", "technical lead", "embedded platform", "embedded systems",
            "api design", "systems integration", "platform customization", "microservices",
            "full stack engineer", "individual contributor", "gcp", "gke", "docker", "kubernetes",
            "vue", "nextjs", "nestjs", "php", "linux", "restful apis", "third-party apis",
            "javascript frameworks", "full stack web development", "github", "notion",
            "full-stack application development", "event-driven microservices", "graphql", "mcp servers",
            "feature engineering", "model optimization", "data preprocessing", "deep learning",
            "go", "sql", "full-stack", "user-facing web applications", "cross-functional teams",
            "product features", "architectural discussions", "shipping complex software projects",
        },
        "phrases": [
            "system design", "distributed systems", "api design", "ci/cd", "technical architecture", "real-time collaboration",
            "forward deployed software engineer", "embedded platform", "embedded systems", "systems integration",
            "platform customization", "technical troubleshooting", "root-cause analysis", "integration workflows",
            "full stack engineer", "end-to-end", "individual contributor", "multiple applications",
            "restful apis", "third-party apis", "full stack web development", "javascript frameworks",
            "event-driven microservices", "graphql", "mcp servers", "high throughput services",
            "cloud on-premises deployment", "user-facing web applications", "cross-functional teams",
            "product features", "architectural discussions", "shipping complex software projects",
        ],
        "boost_words": {
            "python": 3, "java": 2, "typescript": 3, "react": 3, "next.js": 3, "node": 2, "aws": 3, "kubernetes": 2,
            "api": 3, "integration": 3, "embedded": 3, "platform": 2, "architecture": 2, "sdk": 2, "microservices": 2,
            "troubleshooting": 2, "support": 2, "deployment": 2, "implementation": 2, "delivery": 2, "customization": 2,
            "vue": 3, "nextjs": 3, "nestjs": 3, "php": 3, "linux": 2, "restful apis": 3, "third-party apis": 3,
            "github": 2, "notion": 1,
            "graphql": 3, "fastapi": 3, "flask": 2, "angular": 2, "vue.js": 2, "redis": 2,
            "postgresql": 2, "mysql": 2, "feature engineering": 3, "model optimization": 3, "microservices": 3,
            "go": 3, "sql": 3, "full-stack": 3, "user-facing web applications": 2,
            "cross-functional teams": 2, "product features": 2, "architectural discussions": 2,
            "shipping complex software projects": 2,
        },
        "weak_tokens": {"codebase", "coding"},
        "garbage_tokens": set(),
        "filler_phrases": {"clean code mindset"},
    },
    "solutions": {
        "aliases": {
            "customer-facing engineering", "solutions engineering", "developer relations", "customer solution delivery",
            "requirement gathering", "technical discussions", "architecture reviews", "technical escalation",
            "partner technical workshops", "implementation", "adoption", "customer integrations",
        },
        "phrases": [
            "customer-facing engineering", "customer solution delivery", "developer relations", "requirement gathering",
            "architecture reviews", "technical escalation support", "customer-specific development", "technical direction",
            "partner tools", "integration workflows", "developer support", "platform capabilities",
        ],
        "boost_words": {
            "customer": 2, "partner": 2, "partners": 2, "implementation": 2, "delivery": 2,
            "integration": 3, "support": 2, "developer": 2, "architecture": 2, "platform": 2,
        },
        "weak_tokens": set(),
        "garbage_tokens": set(),
        "filler_phrases": {"trusted advisor mindset"},
    },
    "cloud": {
        "aliases": {"gcp", "gke", "docker", "kubernetes", "cloud", "cloud deployed", "container", "containers"},
        "phrases": ["cloud-deployed scripts", "container orchestration", "kubernetes deployment"],
        "boost_words": {"gcp": 3, "gke": 3, "docker": 3, "kubernetes": 3, "cloud": 2, "deployment": 2},
        "weak_tokens": set(),
        "garbage_tokens": set(),
        "filler_phrases": {"cloud native mindset"},
    },
    "data": {
        "aliases": {
            "data engineer", "data engineering", "data pipelines", "sql", "kafka", "databricks", "nifi",
            "data governance", "data architectures", "data processing", "bi", "streaming", "etl",
            "data modeling", "analytics platform", "tableau", "power bi",
        },
        "phrases": [
            "data pipelines", "sql optimization", "complex query design", "kafka streaming", "connector development",
            "databricks workflow development", "medallion architecture", "data governance", "performance tuning",
            "data architectures", "data integration", "privacy best practices", "data security",
            "monitoring solutions", "performance tracking", "dashboarding",
            "data analytics platform", "data modeling", "structured and unstructured data", "business intelligence",
            "working prototypes", "development specifications",
        ],
        "boost_words": {
            "sql": 3, "kafka": 3, "databricks": 3, "nifi": 3, "druid": 2, "mongodb": 2, "opensearch": 2, "postgres": 2,
            "governance": 2, "security": 2, "privacy": 2, "pipelines": 2, "streaming": 2, "architecture": 2, "monitoring": 2,
            "kpi": 2, "kpis": 3, "dashboarding": 2, "tableau": 3, "power bi": 3, "business intelligence": 3,
            "data modeling": 3, "analytics platform": 3, "prototypes": 2,
        },
        "weak_tokens": {"data"},
        "garbage_tokens": set(),
        "filler_phrases": {"data driven culture"},
    },
    "ai": {
        "aliases": {
            "ai", "ml", "mlops", "llm", "rag", "generative ai", "ml pipelines", "models", "training", "deployment", "monitoring",
            "copilot", "power automate", "prompt engineering", "automation governance",
            "numpy", "pandas", "scikit-learn", "tensorflow", "pytorch", "transformers", "deep learning",
            "speech analytics", "sentiment analytics", "intent models", "dialog flows", "agent assist", "dialogflow",
        },
        "phrases": [
            "ml pipelines", "training deployment monitoring", "llm-based solutions", "rag architectures",
            "generative ai", "agent performance", "model evaluation", "intelligent workflow automation",
            "governance models", "automation governance", "workflow automation", "process automation",
            "machine learning model development", "feature engineering", "data preprocessing", "model optimization",
            "domain appropriate metrics", "model performance evaluation", "mlops best practices", "model creation",
            "speech analytics", "sentiment analytics", "intent models", "dialog flows", "self-service automation",
            "agent assist", "automation workflows", "cx analytics",
        ],
        "boost_words": {
            "mlops": 3, "llm": 3, "rag": 3, "generative": 2, "ai": 2, "ml": 2, "deployment": 2, "monitoring": 2,
            "copilot": 3, "power automate": 3, "prompt engineering": 2, "governance": 2, "dataverse": 3,
            "numpy": 3, "pandas": 3, "scikit-learn": 3, "tensorflow": 3, "pytorch": 3, "transformers": 3,
            "feature engineering": 3, "model optimization": 3, "deep learning": 3, "data preprocessing": 2,
            "speech analytics": 3, "sentiment analytics": 3, "intent models": 3, "dialogflow": 3, "agent assist": 3, "cx": 2,
        },
        "weak_tokens": {"ai", "ml"},
        "garbage_tokens": set(),
        "filler_phrases": {"ai first mindset"},
    },
    "product": {
        "aliases": {
            "product manager", "product owner", "roadmap", "prioritization", "discovery", "pm",
            "product-minded", "customer discovery", "development velocity", "end-to-end delivery",
        },
        "phrases": [
            "product strategy", "requirements gathering", "user research", "roadmap planning", "feature prioritization",
            "customer discovery", "end-to-end delivery", "product-minded",
        ],
        "boost_words": {"kpi": 2, "okr": 2, "experimentation": 2, "retention": 2, "adoption": 2},
        "weak_tokens": {"backlog"},
        "garbage_tokens": set(),
        "filler_phrases": {"wear many hats"},
    },
    "design": {
        "aliases": {"designer", "ux", "ui", "product design", "visual design", "brand"},
        "phrases": ["design systems", "interaction design", "user journey", "information architecture", "accessibility standards"],
        "boost_words": {"figma": 2, "prototype": 2, "wireframe": 2, "accessibility": 2},
        "weak_tokens": {"pixel"},
        "garbage_tokens": set(),
        "filler_phrases": {"good eye for design"},
    },
    "marketing": {
        "aliases": {
            "marketing", "growth", "seo", "content", "campaign", "demand generation",
            "marketing representative", "sales and marketing", "customer acquisition",
        },
        "phrases": ["campaign optimization", "conversion rate optimization", "attribution modeling", "funnel analysis"],
        "boost_words": {"seo": 3, "sem": 2, "email": 2, "crm": 2, "analytics": 2, "posthog": 2},
        "weak_tokens": {"creative"},
        "garbage_tokens": set(),
        "filler_phrases": {"brand voice champion"},
    },
    "sales": {
        "aliases": {
            "sales", "account executive", "sdr", "bdr", "pipeline", "business development", "account manager",
            "account management", "prospecting", "lead generation", "outbound", "revenue growth", "client relationships",
            "sales process", "forecasting", "quota", "revenue", "sales improvement",
            "sales representative", "sales operations", "sales presentations", "customer service", "face-to-face",
            "business development representative", "etf wholesaler", "wholesaler", "wholesaling", "advisor relationships",
            "financial advisor", "broker dealer", "territory management", "channel sales",
            "outside sales representative", "field sales", "territory sales", "account coordinator", "inside sales",
            "sales engineer", "solutions engineer", "pre-sales", "solution selling", "technical demos",
        },
        "phrases": [
            "pipeline management", "territory planning", "deal strategy", "customer expansion", "business development",
            "account management", "lead generation", "outbound prospecting", "sales engagement", "revenue growth",
            "new business opportunities", "revenue-focused pipeline", "client activity", "recurring volume",
            "relationship-building", "client experience", "pipeline health", "performance metrics",
            "market trends", "competitive developments", "prospecting strategies", "sales process", "activity tracking",
            "advisor relationships", "business development representative", "etf wholesaler", "territory management",
            "channel partner sales", "broker dealer coverage", "financial advisor outreach", "book of business",
            "outside sales representative", "field sales", "territory sales", "account coordinator",
            "sales territory coverage", "client account support", "channel account support",
            "sales engineering", "solution selling", "technical demos", "pre-sales support",
        ],
        "boost_words": {
            "crm": 3, "salesforce": 2, "forecasting": 2, "quota": 2, "sales": 3, "pipeline": 3,
            "prospecting": 3, "outbound": 2, "lead": 2, "leads": 2, "revenue": 3, "clients": 2,
            "client": 2, "account": 2, "relationships": 2, "relationship": 2, "onboarding": 2, "metrics": 2,
            "targets": 2, "opportunities": 2, "volume": 2, "reporting": 2,
            "wholesaler": 3, "etf": 3, "advisor": 2, "broker dealer": 2, "territory": 2, "book of business": 2,
            "outside sales": 3, "field sales": 3, "account coordinator": 3, "territory sales": 3, "inside sales": 2,
            "sales engineer": 3, "solution selling": 3, "pre-sales": 3, "technical demos": 2,
        },
        "weak_tokens": {"hunter"},
        "garbage_tokens": set(),
        "filler_phrases": {"rockstar salesperson"},
    },
    "finance": {
        "aliases": {
            "finance", "financial", "accounting", "fp&a", "controller", "analyst", "audit", "compliance",
            "foreign exchange", "fx", "global payments", "banknote", "financial institutions", "settlement",
            "profit", "loss", "cash flow", "budgeting", "forecasting", "p&l",
            "fintech", "banking", "modern accounting", "financial infrastructure", "b2b saas",
            "quantitative investment", "investment management", "private markets", "investment decision-making",
            "quantitative research", "liquidity solutions", "securities services", "capital markets",
        },
        "phrases": [
            "financial modeling", "variance analysis", "internal controls", "regulatory compliance",
            "foreign exchange", "global payment solutions", "financial institutions", "commercial prospects",
            "currency needs", "logistics workflows", "decision-making criteria", "banknote solutions",
            "quantitative investment", "investment decision-making", "investment management", "private markets",
            "quantitative research", "business requirements", "liquidity solutions", "securities services",
        ],
        "boost_words": {
            "gaap": 3, "forecasting": 2, "budgeting": 2, "reconciliation": 2, "compliance": 2, "settlement": 2, "fx": 2,
            "quantitative": 3, "investment": 3, "private markets": 3, "investment management": 3, "research": 2,
            "liquidity": 3, "securities": 3,
        },
        "weak_tokens": {"numbers"},
        "garbage_tokens": set(),
        "filler_phrases": {"numbers oriented"},
    },
    "insurance": {
        "aliases": {
            "commercial lines", "account manager", "brokerage", "underwriter", "underwriting", "insurance",
            "policy servicing", "claims", "renewals", "carrier", "risk placement",
        },
        "phrases": [
            "commercial lines account management", "policy administration", "policy servicing", "renewal management",
            "risk placement", "carrier negotiations", "underwriting support", "claims coordination",
        ],
        "boost_words": {
            "insurance": 3, "underwriting": 3, "underwriter": 3, "brokerage": 3, "policy": 2, "renewals": 2,
            "claims": 2, "carrier": 2, "commercial lines": 3,
        },
        "weak_tokens": {"producer"},
        "garbage_tokens": set(),
        "filler_phrases": {"insurance passion"},
    },
    "retail": {
        "aliases": {
            "assistant store manager", "store manager", "retail", "merchandising", "store operations",
            "customer engagement", "floor leadership", "inventory", "outlets",
        },
        "phrases": [
            "store operations", "customer engagement", "visual merchandising", "floor leadership",
            "retail team management", "inventory control", "sales floor operations",
        ],
        "boost_words": {
            "retail": 3, "store": 3, "merchandising": 2, "inventory": 2, "customer engagement": 3,
            "assistant store manager": 3,
        },
        "weak_tokens": {"associate"},
        "garbage_tokens": set(),
        "filler_phrases": {"retail rockstar"},
    },
    "brokerage": {
        "aliases": {
            "brokerage", "underwriter assistants", "underwriter assistant", "securities services",
            "liquidity solutions", "trade support", "client servicing", "portfolio operations",
        },
        "phrases": [
            "brokerage operations", "underwriting workflows", "trade support", "client servicing",
            "liquidity solutions", "securities services", "portfolio operations",
        ],
        "boost_words": {
            "brokerage": 3, "underwriter": 3, "underwriting": 3, "securities": 3, "liquidity": 3, "trade": 2,
        },
        "weak_tokens": {"assistant"},
        "garbage_tokens": set(),
        "filler_phrases": {"brokerage hustle"},
    },
    "operations": {
        "aliases": {
            "operations", "ops", "supply chain", "logistics", "program manager", "process",
            "director of operations", "operator", "execution", "workforce planning", "accountability", "operational", "sops", "performance",
            "turnaround", "business management", "operational turnaround",
            "office manager", "administrative operations", "food production", "production manager", "inventory control",
            "scheduling", "vendor coordination", "facilities coordination",
            "contact center", "ivr", "fcr", "csat", "wfo", "ccaas", "wxcc", "webex", "calabrio",
        },
        "phrases": [
            "process optimization", "service level agreements", "capacity planning", "vendor management",
            "day-to-day operations", "daily operations", "revenue performance", "operational performance",
            "operational inefficiencies", "performance standards", "drive accountability",
            "office administration", "administrative operations", "calendar coordination", "invoice processing",
            "accounts payable", "accounts receivable", "inventory management", "production scheduling",
            "quality assurance", "food safety compliance", "facility operations", "cross-team coordination",
            "contact center", "cisco webex contact center", "calabrio one", "ivr improvements",
            "containment rate", "escalation rate", "customer satisfaction", "support operations", "service desk support",
            "incident triage", "ticket resolution",
        ],
        "boost_words": {
            "sla": 2, "sop": 2, "workflow": 2, "throughput": 2, "operations": 3, "execution": 3,
            "performance": 3, "revenue": 3, "billing": 3, "collections": 3, "kpis": 3, "dashboards": 2,
            "hiring": 2, "recruiting": 2, "efficiency": 2, "implementation": 2,
            "office manager": 3, "administrative": 2, "inventory": 3, "scheduling": 2, "vendor": 2, "invoicing": 2,
            "accounts payable": 3, "accounts receivable": 3, "food safety": 3, "quality assurance": 3, "production": 2,
            "ivr": 3, "fcr": 3, "csat": 3, "contact center": 3, "webex": 3, "calabrio": 3, "wfo": 2, "ccaas": 2, "wxcc": 2,
            "service desk": 3, "incident": 2, "tickets": 2, "triage": 2,
        },
        "weak_tokens": {"busy"},
        "garbage_tokens": set(),
        "filler_phrases": {"wear many hats"},
    },
    "industrial": {
        "aliases": {
            "electrical engineer", "automation engineer", "controls engineer", "industrial engineer", "plc",
            "scada", "hmi", "instrumentation", "control systems", "motor controls", "commissioning",
            "panel design", "electrical schematics", "industrial automation", "process controls",
        },
        "phrases": [
            "industrial automation", "electrical systems", "control systems", "process controls", "plc programming",
            "scada integration", "hmi development", "motor controls", "electrical schematics", "panel design",
            "instrumentation and controls", "field commissioning", "factory automation", "safety interlocks",
        ],
        "boost_words": {
            "plc": 3, "scada": 3, "hmi": 3, "instrumentation": 3, "controls": 3, "electrical": 3,
            "commissioning": 2, "automation": 2, "schematics": 2, "panel": 2, "interlocks": 2,
        },
        "weak_tokens": {"technician"},
        "garbage_tokens": set(),
        "filler_phrases": {"hands-on environment"},
    },
    "aviation": {
        "aliases": {
            "pilot", "first officer", "captain", "flight instructor", "aviation", "flight operations",
            "faa", "aircraft", "flight planning", "flight safety", "instrument rating",
        },
        "phrases": [
            "flight operations", "flight safety", "aircraft systems", "instrument flight rules",
            "flight planning", "crew resource management", "faa compliance", "flight instruction",
        ],
        "boost_words": {
            "pilot": 3, "aviation": 3, "aircraft": 3, "faa": 3, "flight": 3, "captain": 2, "first officer": 2,
            "instrument": 2, "airspace": 2,
        },
        "weak_tokens": {"hours", "current"},
        "garbage_tokens": set(),
        "filler_phrases": {"equal opportunity pilot employer"},
    },
    "marine": {
        "aliases": {
            "naval architect", "marine engineer", "ship design", "vessel", "hull", "stability", "classification society",
            "abs", "bureau veritas", "dnv", "maritime", "offshore",
        },
        "phrases": [
            "naval architecture", "ship design", "stability analysis", "classification compliance",
            "marine structural analysis", "vessel design", "regulatory compliance",
        ],
        "boost_words": {
            "naval": 3, "marine": 3, "architect": 2, "vessel": 2, "hull": 2, "stability": 3, "abs": 3, "dnv": 2,
        },
        "weak_tokens": {"american", "bureau"},
        "garbage_tokens": set(),
        "filler_phrases": {"marine passion"},
    },
    "mechanical": {
        "aliases": {
            "mechanical engineer", "cad designer", "mechanical design", "cad", "solidworks", "autocad",
            "blueprints", "tolerances", "drafting", "assemblies", "manufacturing drawings",
        },
        "phrases": [
            "mechanical design", "cad modeling", "engineering drawings", "gd&t", "design for manufacturing",
            "bill of materials", "tolerance analysis",
        ],
        "boost_words": {
            "mechanical": 3, "cad": 3, "solidworks": 3, "autocad": 3, "blueprints": 2, "drawings": 2, "assemblies": 2,
        },
        "weak_tokens": {"knowledge", "needed"},
        "garbage_tokens": set(),
        "filler_phrases": {"strong mechanical aptitude"},
    },
    "construction": {
        "aliases": {
            "construction", "field engineer", "materials testing", "site inspection", "project site",
            "concrete", "asphalt", "soil testing", "quality control", "safety compliance",
        },
        "phrases": [
            "construction materials testing", "field testing", "site inspection", "project coordination",
            "quality control", "safety compliance", "construction documentation", "materials sampling",
        ],
        "boost_words": {
            "construction": 3, "materials": 2, "field testing": 3, "inspection": 2, "concrete": 2, "asphalt": 2,
            "quality control": 3, "safety": 2, "site": 2,
        },
        "weak_tokens": {"labor"},
        "garbage_tokens": set(),
        "filler_phrases": {"fast paced construction environment"},
    },
    "healthcare": {
        "aliases": {
            "medical assistant", "clinic coordinator", "patient care", "clinical", "healthcare",
            "appointment scheduling", "emr", "ehr", "patient records", "front desk medical",
        },
        "phrases": [
            "patient care", "appointment scheduling", "medical records", "clinical documentation",
            "care coordination", "insurance verification", "patient intake", "provider scheduling",
        ],
        "boost_words": {
            "patient": 3, "clinical": 3, "medical": 3, "ehr": 3, "emr": 3, "scheduling": 2,
            "insurance verification": 2, "care coordination": 3,
        },
        "weak_tokens": {"caregiver"},
        "garbage_tokens": set(),
        "filler_phrases": {"compassionate bedside manner"},
    },
    "education": {
        "aliases": {
            "teacher", "instructor", "classroom", "lesson planning", "curriculum", "student",
            "advanced placement", "ap english", "education", "school",
        },
        "phrases": [
            "classroom instruction", "lesson planning", "curriculum development", "student assessment",
            "behavior management", "learning outcomes", "parent communication",
        ],
        "boost_words": {
            "teacher": 3, "instructor": 3, "classroom": 3, "curriculum": 3, "lesson": 2, "assessment": 2,
            "student": 2, "education": 2,
        },
        "weak_tokens": {"kids"},
        "garbage_tokens": set(),
        "filler_phrases": {"passion for teaching"},
    },
    "legal_admin": {
        "aliases": {
            "legal assistant", "paralegal", "legal documentation", "case management", "docket", "court filing",
            "law office", "litigation support", "document review", "legal research", "pleadings",
            "discovery", "court calendar", "case files",
        },
        "phrases": [
            "legal documentation", "case management", "document review", "court filings",
            "docket management", "litigation support", "client intake", "legal research",
            "discovery support", "court calendar management", "pleadings drafting", "case file maintenance",
        ],
        "boost_words": {
            "legal": 3, "paralegal": 3, "filings": 2, "docket": 2, "litigation": 2, "documentation": 2,
            "research": 2, "pleadings": 2, "discovery": 2, "calendar": 2, "case files": 2,
        },
        "weak_tokens": {"clerical", "graduates", "graduate", "students", "recent", "school"},
        "garbage_tokens": set(),
        "filler_phrases": {"legal rockstar"},
    },
    "legal": {
        "aliases": {"law firm", "legal", "attorney", "managing attorney", "firm"},
        "phrases": ["law firm", "professional services", "law firm financial performance"],
        "boost_words": {"compliance": 2, "regulatory": 2, "governance": 2, "contract": 2},
        "weak_tokens": {"matter"},
        "garbage_tokens": set(),
        "filler_phrases": {"legal ninja"},
    },
}
