from __future__ import annotations

# this file is just kind of an amalgamation of diff dicts for our extraction profile.

# it serves to tell us what to extract and how strong it is.

# --- the minimum number of hits required for a domain to be considered active. --- #
minAliasHits = 2

# --- target role title substrings per domain key, used when scoring which lexicon domains are active (detect_domains). --- #
titleAnchorHints = {
    "operations": {
        "project manager",
        "operations manager",
        "program manager",
        "superintendent",
        "estimator",
        "general manager",
        "restaurant manager",
        "grille manager",
        "hospitality manager",
    },
    "sales": {"account executive", "sales manager", "business development", "account manager"},
    "marketing": {"marketing manager", "assistant marketing manager", "demand generation", "brand manager", "content manager"},
    "finance": {"financial analyst", "controller", "accounting manager", "treasury"},
    "legal": {"legal counsel", "paralegal", "compliance manager"},
    "engineering": {"software engineer", "full stack", "backend", "frontend", "developer", "front end engineer", "front end developer"},
    "data": {"data engineer", "data analyst", "analytics engineer", "data scientist", "machine learning scientist"},
    "ai": {"machine learning engineer", "ai engineer", "ml engineer"},
    "industrial": {"electrical engineer", "automation engineer", "controls engineer", "industrial engineer"},
    "construction": {"construction materials professional", "field technician", "construction engineer", "site inspector"},
    "healthcare": {
        "medical assistant",
        "clinic coordinator",
        "patient coordinator",
        "clinical assistant",
        "psychiatrist",
        "licensed psychiatrist",
        "psychologist",
        "therapist",
        "counselor",
    },
    "education": {"teacher", "summer camp instructor", "advanced placement", "faculty"},
    "legal_admin": {"legal assistant", "paralegal", "litigation assistant"},
    "aviation": {"pilot", "first officer", "captain", "flight instructor"},
    "marine": {"naval architect", "marine engineer"},
    "mechanical": {"cad designer", "mechanical engineer", "mechanical designer"},
    "insurance": {"commercial lines account manager", "account manager", "underwriter", "brokerage"},
    "retail": {"assistant store manager", "store manager", "retail manager"},
    "brokerage": {"underwriter assistant", "brokerage assistant", "securities services associate"},
    "social_media": {
        "content creator",
        "social media creator",
        "tiktok creator",
        "ugc creator",
        "video creator",
        "creator",
        "social media manager",
        "content strategist",
        "influencer",
        "brand ambassador",
        "social media",
    },
    "leadership": {
        "vice president",
        "vp",
        "executive director",
        "chief of staff",
        "director",
        "head of operations",
        "chief operating officer",
        "coo",
        "president",
        "program director",
    },
    "research_development": {
        "r&d",
        "research and development",
        "r&d intern",
        "rd intern",
        "formulation",
        "product development",
        "technical operations",
    },
    "industrial_operations": {
        "plant operator",
        "wastewater",
        "wastewater treatment",
        "treatment plant",
        "operator",
        "environmental utilities",
        "water resources",
        "mechanical equipment",
    },
    "agriculture": {
        "ranch hand",
        "farm hand",
        "livestock",
        "cattle",
        "farm worker",
        "ranch",
        "agriculture",
    },
    "administrative": {
        "human resources",
        "hr",
        "coordinator",
        "administrative assistant",
        "office coordinator",
        "front office",
    },
}

# --- a set of global stop words, aka words that are not relevant to the job description and should be ignored. --- #
globalStopWords = {
    "also",
    "and", "the", "with", "for", "from", "that", "this", "will", "are", "you", "your", "our", "have", "has",
    "into", "about", "job", "role", "candidate", "candidates", "requirements", "requirement", "required", "including",
    "preferred", "qualification", "qualifications", "ability", "abilities", "responsibilities", "responsibility",
    "etc", "etcetera", "misc", "various", "eg", "e.g",
    "any", "but", "not", "often", "one", "other", "others", "plus", "responsible", "such", "using", "want", "what", "worked", "year",
    "eagerness",
    "full",
    # junk fragment from compounds like real-world / real usage—should not surface as a keyword
    "real",
    # overfire in low-signal sales / entry JDs
    "success", "entry", "level",
    # filler / junk as standalone “keywords”
    "their", "able",
    # sentence glue: almost never a skill keyword by itself
    "across", "all", "can", "based", "after", "who", "working",
    # generic requirement / instruction verbs (not skills as standalone terms)
    "accept", "demonstrate", "show", "exhibit", "ensuring",
    # thin layout / CTA noise in creator and short JDs
    "page", "make", "out",
    # HR / struct boilerplate in government and service postings
    "date", "minimum",
    # junk split from "r&d" style abbreviations; prefer phrase "r&d" in research_development
    "r",
    # req/glue and compound fragments (side-by-side, per diem boilerplate, etc.)
    "must", "per", "acceptable", "side",
    # English "go" (careers CTA) is not the Go language; do not let it rank
    "go", "available",
    # schedule / intensifier noise (daily standups, “highly motivated”, etc.)
    "daily", "highly", "active",
    # verb from “answer phones / email”—not a skill keyword
    "answer",
}

# --- a set of global weak tokens, aka words that are relevant to the job description but are not strong enough to be considered a boost word. --- #
# Prefer multi-word phrases (e.g. api-first architectures, data integrity) so umbrella words do not outrank concrete stack.
globalWeakTokens = {
    "api",
    "accountability", "alignment", "approach", "basic", "behavior", "build", "business", "client", "clients", "collaborate",
    "executive", "leadership", "president", "strategic", "vice",
    "core", "values", "customer", "customers",
    "ethic", "innovation", "organizational", "professionalism", "rigor", "tenacity", "transparency", "urgency",
    "communication", "field", "operational",
    "assist", "career", "health", "industry", "process", "program", "term",
    "materials", "sites", "updates",
    "account", "controller", "information", "prepares",
    "decisions", "design", "development", "documentation", "ensure", "execution", "experience", "exposure", "familiarity",
    "feature", "features",
    "goals", "growth", "helping", "expectations", "opportunities",
    "infrastructure", "integration", "inventory", "knowledge", "life",
    "management", "metrics", "operations", "ownership", "partners", "passion", "performance", "personal",
    "platform", "product", "professional", "related", "relationship", "relationships", "skills", "software", "strong",
    "system", "systems", "support", "team", "technical", "tools", "training", "understanding", "vision", "web", "workflow",
    "hands-on",
    "engineering",
}

# --- a set of global filler phrases. --- #
# Resume/culture soft-skill platitudes only. Line-level apply, compliance, and recruiting boilerplate
# live in rules.wrapperSuppressLineSubstrings / rules.complianceFooterSubstrings, not here.
globalFillerPhrases = {
    "best in class",
    "change agents",
    "collaborative",
    "communicates effectively",
    "customer first",
    "detail oriented",
    "driven ambitious",
    "excellent communication skills",
    "functional skills",
    "hands-on training",
    "high standards",
    "impeccable track record",
    "incredible team",
    "inclusive environment",
    "inclusive work environment",
    "innovative",
    "integrity",
    "move fast",
    "nimble learning",
    "open-door policy",
    "passion confidence and tenacity",
    "passionate",
    "personally accountable",
    "proven strategies",
    "ready to work hard",
    "respect and dignity",
    "seat at the table",
    "self starter",
    "self-motivated",
    "sense of humor",
    "situational adaptability",
    "skilled and motivated",
    "socially aware",
    "strong communication skills",
    "team player",
    "unparalleled customer service",
    "works well under pressure",
}

# --- a list of global phrases. --- #
globalPhrases = [
    # compound anchors: beat umbrella tokens (system, platform, build) in phrase pass + ranking.
    "api-first architectures", "event-driven services", "serverless infrastructure", "booking synchronization", "property technology",
    "ai systems", "agent logic", "feedback loops", "evaluation frameworks", "large language models", "labeling systems",
    "data integrity", "audit readiness", "food safety", "regulatory inspections",
    # leadership / executive / nonprofit-ops: prefer phrases over split vice / president / execution / management.
    "vice president", "executive leadership", "people management", "strategic priorities", "operational excellence",
    "organizational capacity", "cross-functional oversight",
    # field / biomedical / imaging (anchor phrases, no separate domain)
    "field service engineer", "diagnostic imaging equipment", "ultrasound systems", "preventative maintenance", "system calibrations",
    "medical devices", "clinical teams",
    # hr / front office (keeps “human resources” and mail/call work from decomposing into junk tokens)
    "human resources", "front office", "phone calls", "administrative tasks", "office supplies", "incoming and outgoing mail",
    "appointments and meetings",
    "stakeholder management", "cross functional collaboration", "end-to-end ownership", "process improvement", "risk mitigation",
    "incident response", "root cause analysis", "data analysis", "business impact", "customer outcomes", "go to market",
    "a/b testing", "ab testing", "user acquisition", "user activation", "user retention",
    "operational performance", "consistent execution", "drive accountability", "workforce planning", "revenue performance",
    "operational inefficiencies", "performance standards", "professional services",
    "business development", "account management", "lead generation", "outbound prospecting", "sales engagement",
    "revenue growth", "new business opportunities", "revenue-focused pipeline", "client activity", "recurring volume",
    "relationship-building", "client experience", "pipeline health", "performance metrics", "market trends",
    "competitive developments", "prospecting strategies", "sales process", "activity tracking",
    "business management", "business ownership", "cash flow forecasting", "profit loss statements", "profit and loss statements",
    "organizational turnaround", "operational turnaround", "financially measurable results", "managing teams",
    "face-to-face interaction", "sales presentations", "customer service", "training and development", "sales operations",
    "forward deployed software engineer", "forward deployed engineer", "customer-facing engineering", "customer-facing",
    "production environments", "cloud infrastructure", "supply chain", "defense",
    "customer solution delivery", "technical lead",
    "platform customization", "embedded platform", "application-layer enhancements", "developer relations",
    "requirement gathering", "architecture reviews", "developer support", "platform capabilities",
    "embedded engineering", "customer systems", "customer success", "interface documentation",
    "business goals", "application-layer components", "service extensions", "rest-based apis", "systems integration",
    "api design", "interface design documents", "technical troubleshooting", "root-cause analysis",
    "technical escalation support", "customer-specific development", "technical direction", "embedded systems",
    "integration workflows", "partner tools",
    "data pipelines", "sql optimization", "complex query design", "kafka streaming", "connector development",
    "databricks workflow development", "medallion architecture", "data governance", "performance tuning",
    "data security", "privacy best practices", "ml pipelines", "training deployment monitoring",
    "data architectures", "ml workloads", "llm-based solutions", "rag architectures", "generative ai",
    "data integration",
    "machine learning",
    "intelligent workflow automation", "internal process enhancements", "internal workflows", "workflow automation",
    "automation governance", "governance models", "process automation", "operational efficiency",
    "monitoring solutions", "performance tracking", "api integration", "cloud-deployed scripts",
    "automation strategies", "dashboarding", "documentation skills",
    "full-stack features", "next.js", "react native", "end-to-end delivery", "customer discovery",
    "technical architecture", "development velocity", "ai dev tooling", "ci/cd", "production-grade web applications",
    "product-minded", "deployment and maintenance", "financial infrastructure", "modern accounting", "banking tools",
    "fintech", "b2b saas",
    "full stack engineer", "end-to-end", "microservices", "individual contributor", "multiple applications",
    "vue", "nextjs", "nestjs", "php", "linux", "restful apis", "third-party apis",
    "full stack web development", "javascript frameworks", "notion",
    "quantitative investment", "investment decision-making", "data analytics platform", "business requirements",
    "development specifications", "working prototypes", "data modeling", "structured and unstructured data",
    "quantitative research", "business intelligence", "private markets", "investment management",
    "model creation", "machine learning model development", "feature engineering", "model optimization",
    "domain appropriate metrics", "model performance evaluation", "event-driven microservices", "graphql",
    "mcp servers", "ai-powered applications", "cloud on-premises deployment", "microsoft azure", "mlops best practices",
    "data preprocessing", "deep learning models", "high throughput services", "fraud prevention",
    "loss prevention", "parcel delivery optimization",
    "speech analytics", "sentiment analytics", "intent models", "dialog flows", "self-service automation",
    "ivr improvements", "agent assist", "cx analytics", "automation workflows", "customer satisfaction",
    "containment rate", "escalation rate", "contact center", "cisco webex contact center", "calabrio one",
    "patient care", "appointment scheduling", "medical records", "clinical documentation", "care coordination",
    "classroom instruction", "lesson planning", "curriculum development", "student assessment", "behavior management",
    "legal documentation", "case management", "document review", "court filings", "docket management",
    "construction materials testing", "field testing", "site inspection", "quality control", "safety compliance",
    "sales engineering", "solution selling", "technical demos", "pre-sales support", "support operations",
    "service desk support", "incident triage", "ticket resolution", "business systems analysis", "requirements analysis",
    "key performance indicators", "data visualization",
    "user-centric", "user centric",
    "early-stage", "early stage",
    "healthcare", "health care",
    "daily deploy", "deploy daily",
    "physician", "practitioners", "practitioner-facing", "practitioner facing",
    "product strategy",
    "early-stage startup", "early stage startup",
    "user-centric product", "user centric product",
]

# --- a dict of global boost words and their strengths. --- #
globalBoostWords = {
    "stakeholder management": 3, "cross functional collaboration": 2, "end-to-end ownership": 3, "process improvement": 3,
    "risk mitigation": 3, "incident response": 3, "root cause analysis": 3, "data analysis": 2, "business impact": 3,
    "customer outcomes": 2, "go to market": 2, "a/b testing": 1, "user acquisition": 3, "user activation": 3, "user retention": 3,
    "revenue": 3, "collections": 3, "billing": 3,
    "kpis": 3, "dashboards": 2, "hiring": 2, "recruiting": 2, "operator": 2, "implementation": 2,
    "sales": 3, "pipeline": 3, "prospecting": 3, "outbound": 2, "lead": 2, "leads": 2, "crm": 3,
    "forecasting": 2, "reporting": 2, "account": 2,
    "onboarding": 2, "metrics": 2, "targets": 2, "opportunities": 2, "volume": 2, "compliance": 2,
    "budgeting": 3, "profit": 3, "cash": 2, "flow": 2, "excel": 2, "turnaround": 3,
    "productivity": 2, "forecasting": 3, "sales": 3, "marketing": 2, "service": 1, "leadership": 1,
    "python": 3, "django": 3, "react": 3, "aws": 3, "apis": 3, "api": 3,
    "embedded": 3, "partners": 2, "developer": 2, "architecture": 2, "sdk": 2, "microservices": 2,
    "troubleshooting": 2, "deployment": 2, "delivery": 2, "customization": 2,
    "sql": 3, "kafka": 3, "databricks": 3, "nifi": 3, "druid": 2, "mongodb": 2, "opensearch": 2, "postgres": 2,
    "governance": 2, "security": 2, "privacy": 2, "mlops": 3, "rag": 3, "llm": 3, "generative": 2,
    "pipelines": 2, "architecture": 2, "monitoring": 2, "streaming": 2,
    "automation": 3, "copilot": 3, "power automate": 3, "power bi": 2, "dataverse": 3, "scripting": 3,
    "kpi": 2, "kpis": 3, "dashboarding": 2, "prompt engineering": 2,
    "typescript": 3, "next.js": 3, "react native": 3, "full-stack": 3, "deployment": 2, "maintenance": 2,
    "fintech": 2, "banking": 2, "accounting": 2, "ci/cd": 2,
    "gcp": 3, "gke": 3, "docker": 3, "kubernetes": 3, "machine learning": 3,
    "nextjs": 3, "nestjs": 3, "php": 3, "linux": 2,
    "restful apis": 3, "third-party apis": 3, "full stack web development": 3, "javascript frameworks": 2,
    "notion": 1,
    "power bi": 3, "business intelligence": 1, "data modeling": 3, "quantitative": 3,
    "investment": 3, "private markets": 3, "investment management": 3, "analytics platform": 3, "prototypes": 2,
    "numpy": 3, "pandas": 3, "scikit-learn": 3, "tensorflow": 3, "pytorch": 3, "transformers": 3,
    "fastapi": 3, "flask": 2, "django": 3, "angular": 2, "vue.js": 3, "graphql": 3,
    "redis": 2, "postgresql": 2, "mysql": 2, "azure": 2, "mlops": 3, "feature engineering": 3,
    "model optimization": 3, "data preprocessing": 2, "deep learning": 3, "microservices": 3,
    "webex": 3, "calabrio": 3, "ivr": 3, "fcr": 3, "csat": 3, "dialogflow": 3, "cx": 2, "wfo": 2, "ccaas": 2, "wxcc": 2,
    "key performance indicators": 2, "ruby": 3, "ruby on rails": 3, "tailwind css": 2, "anthropic claude": 3,
    "ios": 2, "android": 2, "visualization": 2, "automations": 3, "flows": 1,
    "user-centric": 3, "healthcare": 3, "early-stage": 2, "startup": 2,
    "physician": 2, "practitioners": 2, "practitioner": 2, "product strategy": 3,
    "solutions": 1, "components": 1, "frontend": 2, "backend": 2, "mobile": 2,
    "strategy": 1,
    "design": 1, "implement": 1, "build": 1, "deploy": 1, "collaborate": 1, "communicate": 1, "contribute": 1, "share": 1,
    "signup": 1, "founders": 1,
    "ultrasound": 2, "imaging": 2, "equipment": 2, "biomedical": 2, "electronics": 2, "clinical": 2,
}

# --- a dict of global phrase canonicals. --- #
globalPhraseCanonical = {
    "postgres": "postgresql",
    "my sql": "mysql",
    "mongo": "mongodb",
    "js frameworks": "javascript frameworks",
    "javascript framework": "javascript frameworks",
    "js framework": "javascript frameworks",
    "js": "javascript",
    "ts": "typescript",
    "node": "node.js",
    "reactjs": "react",
    "react.js": "react",
    "front-end": "frontend",
    "front end": "frontend",
    "infra-engineer": "infrastructure",
    "infra": "infrastructure",
    "rails": "ruby on rails",
    "tailwind": "tailwind css",
    "claude": "anthropic claude",
    "user centric": "user-centric",
    "early stage": "early-stage",
    "health care": "healthcare",
    "practitioner facing": "practitioner-facing",
    "next js": "next.js",
    "vue": "vue.js",
    "vuejs": "vue.js",
    "vue.js": "vue.js",
    "react-native": "react native",
    "full-stack engineer": "full stack engineer",
    "full stack developer": "full stack engineer",
    "full-stack developer": "full stack engineer",
    "fullstack engineer": "full stack engineer",
    "micro services": "microservices",
    "restful api": "restful apis",
    "restful services": "restful apis",
    "graph ql": "graphql",
    "sklearn": "scikit-learn",
    "ml": "machine learning",
    "ai/ml": "machine learning",
    "ml/ai": "machine learning",
    "ai": "artificial intelligence",
    "llm": "large language models",
    "llms": "large language models",
    "rag": "retrieval augmented generation",
    "m l ops": "mlops",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "dl": "deep learning",
    "ci cd": "continuous integration continuous delivery",
    "containers": "docker",
    "containerization": "docker",
    "k8s": "kubernetes",
    "aws": "amazon web services",
    "gcp": "google cloud platform",
    "gke": "google kubernetes engine",
    "microsoft azure": "azure",
    "azure ai": "azure",
    "azure openai": "azure",
    "azure-native": "azure",
    "azure native": "azure",
    "microsoft power automate": "power automate",
    "power-automate": "power automate",
    "powerautomate": "power automate",
    "microsoft copilot": "copilot",
    "bi": "business intelligence",
    "tableau desktop": "tableau",
    "powerbi": "power bi",
    "power-bi": "power bi",
    "crm": "customer relationship management",
    "sfdc": "salesforce",
    "kpi": "key performance indicators",
    "kpis": "key performance indicators",
    "seo": "search engine optimization",
    "cs": "customer success",
    "csat": "customer satisfaction",
    "fcr": "first call resolution",
    "ccaas": "contact center as a service",
    "ux": "user experience",
    "ui": "user interface",
    "qa": "quality assurance",
    "project mgr": "project management",
    "project mgmt": "project management",
    "pm": "project management",
    "program mgr": "program management",
    "program mgmt": "program management",
    "pgm": "program management",
    "product mgr": "product management",
    "product mgmt": "product management",
    "pdm": "product management",
    "account mgmt": "account management",
    "acct mgmt": "account management",
    "biz dev": "business development",
    "bd": "business development",
    "gtm": "go to market",
    "sem": "search engine marketing",
    "requirement gathering": "requirements gathering",
    "stakeholder mgmt": "stakeholder management",
    "process optimization": "process improvement",
    "continuous improvement": "process improvement",
    "ops efficiency": "operational efficiency",
    "help desk": "service desk support",
    "helpdesk": "service desk support",
    "it support": "service desk support",
    "incident management": "incident response",
    "incident mgmt": "incident response",
    "sop": "standard operating procedures",
    "sops": "standard operating procedures",
    "sla": "service level agreements",
    "slas": "service level agreements",
    "qc": "quality control",
    "fp&a": "financial planning and analysis",
    "fpa": "financial planning and analysis",
    "pnl": "profit loss statements",
    "erp": "enterprise resource planning",
    "ap": "accounts payable",
    "ar": "accounts receivable",
    "saas": "software as a service",
    "b2b saas": "business to business saas",
    "b2b software": "business to business saas",
    "poc": "proof of concept",
    "mvp": "minimum viable product",
    "sme": "subject matter expert",
    "roi": "return on investment",
    "e2e": "end-to-end",
    "oop": "object oriented programming",
    "tdd": "test driven development",
    "dbms": "database management systems",
    "cx": "customer experience",
    "call center": "contact center",
    "hr": "human resources",
    "iam": "identity and access management",
    "sso": "single sign on",
    "mfa": "multi factor authentication",
    "soc": "security operations center",
    "vpc": "virtual private cloud",
    "dlp": "data loss prevention",
    "ab testing": "a/b testing",
    "end to end ownership": "end-to-end ownership",
    "daily operations": "day-to-day operations",
    "sdr": "sales development",
    "bdr": "business development",
    "crm platforms": "crm",
    "sales engagement tools": "sales engagement",
    "performance metrics": "metrics",
    "profit & loss statements": "profit loss statements",
    "profit and loss statements": "profit loss statements",
    "p&l": "profit loss statements",
    "rest-based apis": "api design",
    "apis": "api",
    "integrations": "integration",
    "root cause analysis": "root-cause analysis",
    "interface design documents": "interface documentation",
    "idds": "interface documentation",
    "llm based solutions": "llm-based solutions",
    "powerautomate": "power automate",
    "microsoft copilot": "copilot",
    "fullstack engineer": "full stack engineer",
    "full stack": "full stack engineer",
    "end to end": "end-to-end",
    "nextjs": "next.js",
    "rest api": "restful apis",
    "rest apis": "restful apis",
    "third party apis": "third-party apis",
    "bi": "business intelligence",
    "scikit learn": "scikit-learn",
    "ml ops": "mlops",
    "ai ml": "machine learning model development",
    "vue js": "vue.js",
    "cloud/on-premises": "cloud on-premises deployment",
    "cross-functional teams": "cross functional collaboration",
    "architectural discussions": "technical architecture",
    "user facing web applications": "user-facing web applications",
}

# --- a set of short tokens allowed as stack tokens despite length (sql, api, aws, etc.). --- #
globalAllowShortTokens = {
    "c++", 
    "c#", 
    "ai", 
    "ml", 
    "ui", 
    "ux", 
    "qa", 
    "cx", 
    "ivr", 
    "fcr", 
    "csat", 
    "wfo", 
    "ccaas", 
    "wxcc",
}

# --- a dict of domains and their aliases, phrases, boost words, and weak tokens. --- #
domainDicts = {
    "engineering": {
        "aliases": {
            "engineer", "engineering", "developer", "software", "frontend", "backend", "full stack", "platform",
            "forward deployed", "software engineer", "technical lead", "embedded platform", "embedded systems",
            "api design", "systems integration", "platform customization", "microservices",
            "full stack engineer", "individual contributor", "gcp", "gke", "docker", "kubernetes",
            "vue", "vue.js", "nextjs", "nestjs", "php", "linux", "restful apis", "third-party apis",
            "javascript frameworks", "full stack web development", "github", "notion",
            "full-stack application development", "event-driven microservices", "graphql", "mcp servers",
            "feature engineering", "model optimization", "data preprocessing", "deep learning",
            "sql", "full-stack", "user-facing web applications", "cross-functional teams",
            "product features", "architectural discussions", "shipping complex software projects",
            "ruby", "ruby on rails", "tailwind css", "anthropic claude", "ios", "android",
            "infrastructure", "components", "software", "solutions", "frontend", "backend", "mobile", "web",
        },
        "phrases": [
            "api-first architectures", "event-driven services", "serverless infrastructure", "booking synchronization", "property technology",
            "system design", "distributed systems", "api design", "ci/cd", "technical architecture", "real-time collaboration",
            "forward deployed software engineer", "embedded platform", "embedded systems", "systems integration",
            "platform customization", "technical troubleshooting", "root-cause analysis", "integration workflows",
            "full stack engineer", "end-to-end", "individual contributor", "multiple applications",
            "restful apis", "third-party apis", "full stack web development", "javascript frameworks",
            "event-driven microservices", "graphql", "mcp servers", "high throughput services",
            "cloud on-premises deployment", "user-facing web applications", "cross-functional teams",
            "product features", "architectural discussions", "shipping complex software projects",
            "daily deploy", "deploy daily", "user-centric product", "early-stage",
        ],
        "boostWords": {
            "python": 3, "java": 2, "typescript": 3, "react": 3, "next.js": 3, "node": 2, "aws": 3, "kubernetes": 2,
            "api": 3, "integration": 1, "embedded": 3, "architecture": 2, "sdk": 2, "microservices": 2,
            "troubleshooting": 2, "deployment": 2, "implementation": 2, "delivery": 2, "customization": 2,
            "vue.js": 3, "nextjs": 3, "nestjs": 3, "php": 3, "linux": 2, "restful apis": 3, "third-party apis": 3,
            "github": 1, "notion": 1,
            "graphql": 3, "fastapi": 3, "flask": 2, "angular": 2, "vue.js": 3, "redis": 2,
            "postgresql": 2, "mysql": 2, "feature engineering": 3, "model optimization": 3, "microservices": 3,
            "sql": 3, "full-stack": 3, "user-facing web applications": 2,
            "cross-functional teams": 2, "product features": 2, "architectural discussions": 2,
            "shipping complex software projects": 2,
            "ruby": 3, "ruby on rails": 3, "tailwind css": 2, "anthropic claude": 3, "ios": 2, "android": 2,
            "frontend": 2, "backend": 2, "mobile": 2,
            "deploy": 2, "implement": 2, "build": 1, "design": 2, "collaborate": 1,
            "user-centric": 2, "automations": 2,
        },
        "weakTokens": {"codebase", "coding"},
    },
    "solutions": {
        "aliases": {
            "customer-facing engineering", "solutions engineering", "developer relations", "customer solution delivery",
            "requirement gathering", "technical discussions", "architecture reviews", "technical escalation",
            "partner technical workshops", "implementation", "adoption", "customer integrations",
        },
        "phrases": [
            "customer-facing engineering", "customer solution delivery", "developer relations", "requirement gathering",
            "architecture reviews", "technical escalation support", "customer-specific development", "technical direction",
            "partner tools", "integration workflows", "developer support", "platform capabilities",
        ],
        "boostWords": {
            "customer": 2, "partner": 2, "partners": 2, "implementation": 2, "delivery": 2,
            "integration": 1, "developer": 2, "architecture": 2,
            "communicate": 1, "collaborate": 1, "contribute": 1, "share": 1,
        },
        "weakTokens": set(),
    },
    "cloud": {
        "aliases": {"gcp", "gke", "docker", "kubernetes", "cloud", "cloud deployed", "container", "containers"},
        "phrases": ["cloud-deployed scripts", "container orchestration", "kubernetes deployment"],
        "boostWords": {"gcp": 3, "gke": 3, "docker": 3, "kubernetes": 3, "cloud": 2, "deployment": 2},
        "weakTokens": set(),
    },
    "data": {
        "aliases": {
            "data engineer", "data engineering", "data pipelines", "sql", "kafka", "databricks", "nifi",
            "data governance", "data architectures", "data processing", "bi", "streaming", "etl",
            "data modeling", "analytics platform", "tableau", "power bi", "data visualization", "automations", "flows",
        },
        "phrases": [
            "data engineering",
            "data science",
            "data warehousing",
            "etl pipelines",
            "elt pipelines",
            "data pipelines", "sql optimization", "complex query design", "kafka streaming", "connector development",
            "databricks workflow development", "medallion architecture", "data governance", "performance tuning",
            "data architectures", "data integration", "privacy best practices", "data security",
            "monitoring solutions", "performance tracking", "dashboarding",
            "data analytics platform", "data modeling", "structured and unstructured data", "business intelligence",
            "working prototypes", "development specifications", "data visualization",
        ],
        "boostWords": {
            "sql": 3, "kafka": 3, "databricks": 3, "nifi": 3, "druid": 2, "mongodb": 2, "opensearch": 2, "postgres": 2,
            "governance": 2, "security": 2, "privacy": 2, "pipelines": 2, "streaming": 2, "architecture": 2, "monitoring": 2,
            "kpi": 2, "kpis": 3, "dashboarding": 2, "tableau": 1, "power bi": 3, "business intelligence": 1,
            "data modeling": 3, "analytics platform": 3, "prototypes": 2,
            "visualization": 2, "automations": 2, "flows": 1,
        },
        "weakTokens": {"data"},
    },
    "ai": {
        "aliases": {
            "ai", "ml", "mlops", "llm", "rag", "generative ai", "ml pipelines", "models", "training", "deployment", "monitoring",
            "copilot", "power automate", "prompt engineering", "automation governance",
            "numpy", "pandas", "scikit-learn", "tensorflow", "pytorch", "transformers", "deep learning",
            "speech analytics", "sentiment analytics", "intent models", "dialog flows", "agent assist", "dialogflow",
        },
        "phrases": [
            "machine learning",
            "ai systems",
            "large language models",
            "agent logic",
            "agents",
            "retrieval",
            "feedback loops",
            "evaluation frameworks",
            "semantic search", "embeddings", "vector databases", "structured outputs", "prompt orchestration",
            "ml pipelines", "training deployment monitoring", "llm-based solutions", "rag architectures",
            "generative ai", "agent performance", "model evaluation", "intelligent workflow automation",
            "governance models", "automation governance", "workflow automation", "process automation",
            "machine learning model development", "feature engineering", "data preprocessing", "model optimization",
            "domain appropriate metrics", "model performance evaluation", "mlops best practices", "model creation",
            "speech analytics", "sentiment analytics", "intent models", "dialog flows", "self-service automation",
            "agent assist", "automation workflows", "cx analytics",
        ],
        "boostWords": {
            "machine learning": 3, "mlops": 3, "llm": 3, "rag": 3, "generative": 2, "ai": 2, "ml": 2,
            "deployment": 2, "monitoring": 2,
            "copilot": 3, "power automate": 3, "prompt engineering": 2, "governance": 2, "dataverse": 3,
            "numpy": 3, "pandas": 3, "scikit-learn": 3, "tensorflow": 3, "pytorch": 3, "transformers": 3,
            "feature engineering": 3, "model optimization": 3, "deep learning": 3, "data preprocessing": 2,
            "speech analytics": 3, "sentiment analytics": 3, "intent models": 3, "dialogflow": 3, "agent assist": 3, "cx": 2,
            "anthropic claude": 3,
        },
        "weakTokens": {"ai", "ml", "learning", "model", "models"},
    },
    "product": {
        "aliases": {
            "product manager", "product owner", "roadmap", "prioritization", "discovery", "pm",
            "product-minded", "customer discovery", "development velocity", "end-to-end delivery",
            "signup", "founders", "user-centric", "consumer",
        },
        "phrases": [
            "product strategy", "requirements gathering", "user research", "roadmap planning", "feature prioritization",
            "customer discovery", "end-to-end delivery", "product-minded",
            "user-centric", "user centric", "early-stage startup", "early stage startup",
        ],
        "boostWords": {
            "kpi": 2, "okr": 2, "experimentation": 2, "retention": 2, "adoption": 2,
            "strategy": 2, "signup": 1, "founders": 1, "user-centric": 3, "consumer": 1,
            "product strategy": 3, "early-stage": 2, "startup": 2, "healthcare": 2,
        },
        "weakTokens": {"backlog"},
    },
    "design": {
        "aliases": {"designer", "ux", "ui", "product design", "visual design", "brand"},
        "phrases": ["design systems", "interaction design", "user journey", "information architecture", "accessibility standards"],
        "boostWords": {"figma": 2, "prototype": 2, "wireframe": 2, "accessibility": 2},
        "weakTokens": {"pixel"},
    },
    "marketing": {
        "aliases": {
            "marketing", "growth", "seo", "content", "campaign", "demand generation",
            "marketing representative", "sales and marketing", "customer acquisition", "signup",
        },
        "phrases": ["campaign optimization", "conversion rate optimization", "attribution modeling", "funnel analysis"],
        "boostWords": {"seo": 3, "sem": 2, "email": 2, "crm": 2, "analytics": 2, "posthog": 2},
        "weakTokens": {"creative"},
    },
    "social_media": {
        "aliases": {
            "content creator", "social media", "social media manager", "tiktok creator", "ugc creator",
            "video creator", "influencer", "content strategist", "brand ambassador", "creator",
            "tiktok", "instagram", "youtube", "ugc", "reels", "short-form",
        },
        "phrases": [
            "content creator", "social media", "short videos", "video editing", "social media handles",
            "tiktok trends", "brand page", "content creation", "short-form video", "talking-style video",
        ],
        "boostWords": {
            "tiktok": 3, "instagram": 3, "youtube": 3, "creator": 3, "content": 2, "video": 3, "videos": 2,
            "editing": 2, "brand": 2, "social": 2, "media": 2, "ugc": 3, "reels": 2, "short-form": 2,
        },
        "weakTokens": set(),
    },
    "leadership": {
        "aliases": {
            "vice president", "executive director", "chief of staff", "head of operations", "chief operating officer",
            "coo", "vp", "program director", "president", "executive", "strategic", "mission", "nonprofit",
        },
        "phrases": [
            "vice president", "executive leadership", "people management", "strategic priorities", "operational excellence",
            "organizational capacity", "cross-functional oversight", "external representation", "mission alignment",
        ],
        "boostWords": {
            "strategy": 3, "strategic": 2, "leadership": 3, "executive": 2, "oversight": 2, "operations": 2, "management": 2,
            "organizational": 2, "mission": 2,
        },
        "weakTokens": set(),
    },
    "research_development": {
        "aliases": {
            "r&d", "research and development", "formulation", "r&d intern", "rd intern", "product development",
            "technical operations", "chemical engineering", "cosmetic science", "chemistry", "biology",
            "raw material", "plm", "product lifecycle", "cosmetics", "consumer goods", "personal care",
            "regulatory", "manufacturing", "specright", "lab",
        },
        "phrases": [
            "r&d", "research and development",
            "raw material", "formula records", "technical documentation", "safety data sheets", "regulatory information",
            "data management", "product lifecycle management", "plm systems", "portfolio management", "formulation",
            "cosmetic science", "regulatory affairs", "consumer goods", "personal care", "structured technical information",
            "contract manufacturing organizations",
        ],
        "boostWords": {
            "plm": 3, "specright": 3, "formulation": 3, "regulatory": 2, "documentation": 2, "raw material": 2,
            "chemistry": 2, "biology": 2, "cosmetic": 2, "manufacturing": 2, "consumer": 2, "portfolio": 2, "lifecycle": 2,
        },
        "weakTokens": set(),
    },
    "industrial_operations": {
        "aliases": {
            "plant operator", "wastewater", "wastewater treatment", "treatment plant", "operator", "treatment", "plant",
            "environmental utilities", "water resources", "mechanical equipment", "mechanical", "environmental", "utilities",
        },
        "phrases": [
            "wastewater treatment", "treatment plant", "plant operator", "mechanical equipment", "mechanical processes",
            "environmental utilities", "water resources control board", "operator certificate",
        ],
        "boostWords": {
            "wastewater": 3, "treatment": 2, "plant": 2, "operator": 3, "mechanical": 2, "utilities": 2, "environmental": 2,
            "water": 2, "certificate": 2, "license": 2,
        },
        "weakTokens": set(),
    },
    "agriculture": {
        "aliases": {
            "ranch hand", "farm hand", "livestock", "cattle", "farm worker", "ranch", "agriculture", "rancher",
            "artificial insemination", "calving", "pasture", "pastures", "harvest", "fence", "fencing", "cdl", "farm",
        },
        "phrases": [
            "ranch hand", "livestock inspections", "artificial insemination", "cattle health", "farm cdl", "horseback riding",
            "general maintenance", "semi-truck", "calving",
        ],
        "boostWords": {
            "cattle": 3, "livestock": 3, "ranch": 2, "farm": 2, "calving": 2, "harvest": 2, "fence": 2,
            "insemination": 2, "horseback": 2, "cdl": 2,
        },
        "weakTokens": set(),
    },
    "administrative": {
        "aliases": {
            "human resources", "hr", "administrative", "office", "receptionist", "front desk", "coordinator", "bilingual",
            "administrative assistant", "office coordinator", "front office", "excel", "appointments", "meetings",
        },
        "phrases": [
            "human resources", "front office", "phone calls", "administrative tasks", "office supplies", "appointments and meetings",
            "incoming and outgoing mail", "mail and emails",
        ],
        "boostWords": {
            "office": 2, "administrative": 2, "excel": 2, "bilingual": 2, "coordinator": 2, "appointments": 2, "meetings": 2,
        },
        "weakTokens": set(),
    },
    "sales": {
        "aliases": {
            "sales", "account executive", "sdr", "bdr", "pipeline", "business development", "account manager",
            "account management", "prospecting", "lead generation", "outbound", "revenue growth", "client relationships",
            "sales process", "forecasting", "quota", "revenue", "sales improvement",
            "sales representative", "sales operations", "sales presentations", "customer service", "face-to-face",
            "business development representative", "etf wholesaler", "wholesaler", "wholesaling", "advisor relationships",
            "financial advisor", "broker dealer", "territory management", "channel sales",
            "outside sales representative", "field sales", "territory sales", "account coordinator", "inside sales",
            "sales engineer", "solutions engineer", "pre-sales", "solution selling", "technical demos",
        },
        "phrases": [
            "pipeline management", "territory planning", "deal strategy", "customer expansion", "business development",
            "account management", "lead generation", "outbound prospecting", "sales engagement", "revenue growth",
            "new business opportunities", "revenue-focused pipeline", "client activity", "recurring volume",
            "relationship-building", "client experience", "pipeline health", "performance metrics",
            "market trends", "competitive developments", "prospecting strategies", "sales process", "activity tracking",
            "advisor relationships", "business development representative", "etf wholesaler", "territory management",
            "channel partner sales", "broker dealer coverage", "financial advisor outreach", "book of business",
            "outside sales representative", "field sales", "territory sales", "account coordinator",
            "sales territory coverage", "client account support", "channel account support",
            "sales engineering", "solution selling", "technical demos", "pre-sales support",
        ],
        "boostWords": {
            "crm": 3, "salesforce": 2, "forecasting": 2, "quota": 2, "sales": 3, "pipeline": 3,
            "prospecting": 3, "outbound": 2, "lead": 2, "leads": 2, "revenue": 3, "clients": 2,
            "client": 2, "account": 2, "relationships": 2, "relationship": 2, "onboarding": 2, "metrics": 2,
            "targets": 2, "opportunities": 2, "volume": 2, "reporting": 2,
            "wholesaler": 3, "etf": 3, "advisor": 2, "broker dealer": 2, "territory": 2, "book of business": 2,
            "outside sales": 3, "field sales": 3, "account coordinator": 3, "territory sales": 3, "inside sales": 2,
            "sales engineer": 3, "solution selling": 3, "pre-sales": 3, "technical demos": 2,
        },
        "weakTokens": {"hunter"},
    },
    "finance": {
        "aliases": {
            "finance", "financial", "accounting", "fp&a", "controller", "analyst", "audit", "compliance",
            "foreign exchange", "fx", "global payments", "banknote", "financial institutions", "settlement",
            "profit", "loss", "cash flow", "budgeting", "forecasting", "p&l",
            "fintech", "banking", "modern accounting", "financial infrastructure", "b2b saas",
            "quantitative investment", "investment management", "private markets", "investment decision-making",
            "quantitative research", "liquidity solutions", "securities services", "capital markets",
        },
        "phrases": [
            "financial modeling", "variance analysis", "internal controls", "regulatory compliance",
            "foreign exchange", "global payment solutions", "financial institutions", "commercial prospects",
            "currency needs", "logistics workflows", "decision-making criteria", "banknote solutions",
            "quantitative investment", "investment decision-making", "investment management", "private markets",
            "quantitative research", "business requirements", "liquidity solutions", "securities services",
        ],
        "boostWords": {
            "gaap": 3, "forecasting": 2, "budgeting": 2, "reconciliation": 2, "compliance": 2, "settlement": 2, "fx": 2,
            "quantitative": 3, "investment": 3, "private markets": 3, "investment management": 3, "research": 2,
            "liquidity": 3, "securities": 3,
        },
        "weakTokens": {"numbers"},
    },
    "insurance": {
        "aliases": {
            "commercial lines", "account manager", "brokerage", "underwriter", "underwriting", "insurance",
            "policy servicing", "claims", "renewals", "carrier", "risk placement",
        },
        "phrases": [
            "commercial lines account management", "policy administration", "policy servicing", "renewal management",
            "risk placement", "carrier negotiations", "underwriting support", "claims coordination",
        ],
        "boostWords": {
            "insurance": 3, "underwriting": 3, "underwriter": 3, "brokerage": 3, "policy": 2, "renewals": 2,
            "claims": 2, "carrier": 2, "commercial lines": 3,
        },
        "weakTokens": {"producer"},
    },
    "retail": {
        "aliases": {
            "assistant store manager", "store manager", "retail", "merchandising", "store operations",
            "customer engagement", "floor leadership", "inventory", "outlets",
        },
        "phrases": [
            "store operations", "customer engagement", "visual merchandising", "floor leadership",
            "retail team management", "inventory control", "sales floor operations",
        ],
        "boostWords": {
            "retail": 3, "store": 3, "merchandising": 2, "inventory": 2, "customer engagement": 3,
            "assistant store manager": 3,
        },
        "weakTokens": {"associate"},
    },
    "brokerage": {
        "aliases": {
            "brokerage", "underwriter assistants", "underwriter assistant", "securities services",
            "liquidity solutions", "trade support", "client servicing", "portfolio operations",
        },
        "phrases": [
            "brokerage operations", "underwriting workflows", "trade support", "client servicing",
            "liquidity solutions", "securities services", "portfolio operations",
        ],
        "boostWords": {
            "brokerage": 3, "underwriter": 3, "underwriting": 3, "securities": 3, "liquidity": 3, "trade": 2,
        },
        "weakTokens": {"assistant"},
    },
    "operations": {
        "aliases": {
            "operations", "ops", "supply chain", "logistics", "program manager", "process",
            "director of operations", "operator", "execution", "workforce planning", "accountability", "operational", "sops", "performance",
            "turnaround", "business management", "operational turnaround",
            "office manager", "administrative operations", "food production", "production manager", "inventory control",
            "scheduling", "vendor coordination", "facilities coordination",
            "contact center", "ivr", "fcr", "csat", "wfo", "ccaas", "wxcc", "webex", "calabrio", "founders",
        },
        "phrases": [
            "resource allocation", "logistics coordination", "dispatch systems", "field operations", "safety regulations",
            "labor regulations",
            "process optimization", "service level agreements", "capacity planning", "vendor management",
            "day-to-day operations", "daily operations", "daily deploy", "deploy daily",
            "early-stage startup", "early stage startup",
            "revenue performance", "operational performance",
            "operational inefficiencies", "performance standards", "drive accountability",
            "office administration", "administrative operations", "calendar coordination", "invoice processing",
            "accounts payable", "accounts receivable", "inventory management", "production scheduling",
            "quality assurance", "food safety compliance", "food safety", "facility operations", "cross-team coordination",
            "traceability", "labeling systems", "inventory control", "data integrity", "audit readiness",
            "regulatory inspections",
            "contact center", "cisco webex contact center", "calabrio one", "ivr improvements",
            "containment rate", "escalation rate", "customer satisfaction", "support operations", "service desk support",
            "incident triage", "ticket resolution",
        ],
        "boostWords": {
            "sla": 2, "sop": 2, "workflow": 2, "throughput": 2, "operations": 3, "execution": 3,
            "performance": 3, "revenue": 3, "billing": 3, "collections": 3, "kpis": 3, "dashboards": 2,
            "hiring": 2, "recruiting": 2, "efficiency": 2, "implementation": 2,
            "office manager": 3, "administrative": 2, "inventory": 3, "scheduling": 2, "vendor": 2, "invoicing": 2,
            "accounts payable": 3, "accounts receivable": 3, "food safety": 3, "quality assurance": 3, "production": 2,
            "ivr": 3, "fcr": 3, "csat": 3, "contact center": 3, "webex": 3, "calabrio": 3, "wfo": 2, "ccaas": 2, "wxcc": 2,
            "service desk": 3, "incident": 2, "tickets": 2, "triage": 2,
        },
        "weakTokens": {"busy"},
    },
    "industrial": {
        "aliases": {
            "electrical engineer", "automation engineer", "controls engineer", "industrial engineer", "plc",
            "scada", "hmi", "instrumentation", "control systems", "motor controls", "commissioning",
            "panel design", "electrical schematics", "industrial automation", "process controls",
        },
        "phrases": [
            "industrial automation", "electrical systems", "control systems", "process controls", "plc programming",
            "scada integration", "hmi development", "motor controls", "electrical schematics", "panel design",
            "instrumentation and controls", "field commissioning", "factory automation", "safety interlocks",
        ],
        "boostWords": {
            "plc": 3, "scada": 3, "hmi": 3, "instrumentation": 3, "controls": 3, "electrical": 3,
            "commissioning": 2, "automation": 2, "schematics": 2, "panel": 2, "interlocks": 2,
        },
        "weakTokens": {"technician"},
    },
    "aviation": {
        "aliases": {
            "pilot", "first officer", "captain", "flight instructor", "aviation", "flight operations",
            "faa", "aircraft", "flight planning", "flight safety", "instrument rating",
        },
        "phrases": [
            "flight operations", "flight safety", "aircraft systems", "instrument flight rules",
            "flight planning", "crew resource management", "faa compliance", "flight instruction",
        ],
        "boostWords": {
            "pilot": 3, "aviation": 3, "aircraft": 3, "faa": 3, "flight": 3, "captain": 2, "first officer": 2,
            "instrument": 2, "airspace": 2,
        },
        "weakTokens": {"hours", "current"},
    },
    "marine": {
        "aliases": {
            "naval architect", "marine engineer", "ship design", "vessel", "hull", "stability", "classification society",
            "abs", "bureau veritas", "dnv", "maritime", "offshore",
        },
        "phrases": [
            "naval architecture", "ship design", "stability analysis", "classification compliance",
            "marine structural analysis", "vessel design", "regulatory compliance",
        ],
        "boostWords": {
            "naval": 3, "marine": 3, "architect": 2, "vessel": 2, "hull": 2, "stability": 3, "abs": 3, "dnv": 2,
        },
        "weakTokens": {"american", "bureau"},
    },
    "mechanical": {
        "aliases": {
            "mechanical engineer", "cad designer", "mechanical design", "cad", "solidworks", "autocad",
            "blueprints", "tolerances", "drafting", "assemblies", "manufacturing drawings",
        },
        "phrases": [
            "mechanical design", "cad modeling", "engineering drawings", "gd&t", "design for manufacturing",
            "bill of materials", "tolerance analysis",
        ],
        "boostWords": {
            "mechanical": 3, "cad": 3, "solidworks": 3, "autocad": 3, "blueprints": 2, "drawings": 2, "assemblies": 2,
        },
        "weakTokens": {"knowledge", "needed"},
    },
    "construction": {
        "aliases": {
            "construction", "field engineer", "materials testing", "site inspection", "project site",
            "concrete", "asphalt", "soil testing", "quality control", "safety compliance",
        },
        "phrases": [
            "resource allocation", "job sites", "schedule conflicts", "punch list", "subcontractors", "material delays",
            "construction materials testing", "field testing", "site inspection", "project coordination",
            "quality control", "safety compliance", "construction documentation", "materials sampling",
        ],
        "boostWords": {
            "construction": 3, "materials": 2, "field testing": 3, "inspection": 2, "concrete": 2, "asphalt": 2,
            "quality control": 3, "safety": 2, "site": 2,
        },
        "weakTokens": {"labor"},
    },
    "healthcare": {
        "aliases": {
            "medical assistant", "clinic coordinator", "patient care", "clinical", "healthcare",
            "appointment scheduling", "emr", "ehr", "patient records", "front desk medical",
            "health", "physicians", "physician", "practitioner", "user-centric", "consumer",
        },
        "phrases": [
            "patient care", "appointment scheduling", "medical records", "clinical documentation",
            "care coordination", "insurance verification", "patient intake", "provider scheduling",
            "healthcare", "health care", "physician", "practitioners", "practitioner-facing", "practitioner facing",
            "user-centric", "user centric",
        ],
        "boostWords": {
            "patient": 3, "clinical": 3, "medical": 3, "ehr": 3, "emr": 3, "scheduling": 2,
            "insurance verification": 2, "care coordination": 3,
            "health": 2, "physicians": 2, "practitioner": 2, "consumer": 1, "user-centric": 3,
            "healthcare": 3, "physician": 2, "practitioners": 2, "product strategy": 2,
        },
        "weakTokens": {"caregiver"},
    },
    "education": {
        "aliases": {
            "teacher", "instructor", "classroom", "lesson planning", "curriculum", "student",
            "advanced placement", "ap english", "education", "school",
        },
        "phrases": [
            "classroom instruction", "lesson planning", "curriculum development", "student assessment",
            "behavior management", "learning outcomes", "parent communication",
        ],
        "boostWords": {
            "teacher": 3, "instructor": 3, "classroom": 3, "curriculum": 3, "lesson": 2, "assessment": 2,
            "student": 2, "education": 2,
        },
        "weakTokens": {"kids"},
    },
    "legal_admin": {
        "aliases": {
            "legal assistant", "paralegal", "legal documentation", "case management", "docket", "court filing",
            "law office", "litigation support", "document review", "legal research", "pleadings",
            "discovery", "court calendar", "case files",
        },
        "phrases": [
            "legal documentation", "case management", "document review", "court filings",
            "docket management", "litigation support", "client intake", "legal research",
            "discovery support", "court calendar management", "pleadings drafting", "case file maintenance",
        ],
        "boostWords": {
            "legal": 3, "paralegal": 3, "filings": 2, "docket": 2, "litigation": 2, "documentation": 2,
            "research": 2, "pleadings": 2, "discovery": 2, "calendar": 2, "case files": 2,
        },
        "weakTokens": {"clerical", "graduates", "graduate", "students", "recent", "school"},
    },
    "legal": {
        "aliases": {"law firm", "legal", "attorney", "managing attorney", "firm"},
        "phrases": ["law firm", "professional services", "law firm financial performance"],
        "boostWords": {"compliance": 2, "regulatory": 2, "governance": 2, "contract": 2},
        "weakTokens": {"matter"},
    },
}
