"""static token and pattern lists for job-description keyword extraction (used by extractor)."""

from __future__ import annotations

# this file serves to tell us how to get rid of the bullshit in the job description.
# does this through helping us downrank the lines structurally and semantically.

# section title prefixes: still extract from these blocks but multiply scores by downweight factor.
# Suppress (below) is checked first in the extractor — no overlap needed.
sectionHeadersToDownweight = {
    "our values",
    "job type",
    "note",
    "value statement",
    "competencies",
    "required education & experience",
}


# section title prefixes: treat as role-relevant body text (responsibilities, requirements, etc.).
roleSectionHeaders = {
    "about the position",
    "about the role",
    "about this role",
    "in this role",
    "job description",
    "must have",
    "overview",
    "qualified candidates will have",
    "role overview",
    "why this role is remarkable",
    "what you will do",
    "what you ll do",
    "responsibilities",
    "key responsibilities",
    "requirements",
    "key qualifications",
    "qualifications",
    "nice to have",
    "preferred qualifications",
    "ideal candidate",
    "you might be the right person for the job if you",
}

# section title prefixes: not core role content (benefits, apply, about company); used to classify lines.
nonRoleSectionHeaders = {
    "who we are",
    "next steps",
    "our benefits",
    "benefits",
    "perks",
    "compensation",
    "compensation package",
    "compensation range",
    "equal opportunity",
    "equal employment opportunity",
    "by clicking apply",
    "apply today",
    "about us",
    "why join us",
    "what s in it for you",
    "what's in it for you",
    "our promise to you",
    "some of our perks",
    "one last thing to ask yourself",
    "about our culture",
    "about our company",
    "our part employees expectations for the company",
    "our part employees",
    "disclaimers",
    "job benefits",
}

hardNoiseTokens = {
    "recruiter",
    "network",
    "step",
    "steps",
    "talk",
    "spin",
    "free",
    "fake",
    "apply",
    "application",
    "dream",
    "job",
    "jobs",
    "recruiting",
    "employment",
    "eligible",
    "privacy",
    "opt",
    "supported",
    "eligible",
    "employment",
    "privacy",
    "citizenship",
    "resident",
    "background",
    "check",
    "checks",
    "disability",
    "veteran",
    "criminal",
    "drug",
    "felony",
    "misdemeanor",
    "conviction",
    "authorization",
    "authorized",
    "agency",
    "fax",
    "placement",
    "referred",
    "resume",
    "resumes",
    "unsolicited",
    "known",
    "groma",
    "lennar",
    "classicorps",
    "https",
    "reflectmegirls",
    "reflectmedolls.com",
    "sanjana",
    "freedomind.us",
}

# tokens that dominate benefit/comp lines; used to penalize phrases that look like perks not skills.
benefitNoiseTokens = {
    "company",
    "paid",
    "employee",
    "insurance",
    "benefits",
    "vacation",
    "holidays",
    "bonus",
    "bonuses",
    "compensation",
    "commission",
    "commissions",
    "allowance",
    "gas",
    "draw",
    "earnings",
    "coverage",
    "comprehensive",
    "weekly",
    "work",
    "sick",
    "off",
    "pto",
    "leave",
    "beef",
    "pickup",
    "disability",
    "referral",
}

# bucket from debugging.
keywordTrashTokens = {
    "dreamer",
    "fun",
    "great",
    "reality",
    "recharge",
    "sleep",
    "sleeper",
    "tons",
}

# stopwords at start/end of ngrams: phrases shouldn't start or end on these (weak boundaries).
connectorEdgeWords = {
    "a",
    "an",
    "and",
    "as",
    "at",
    "for",
    "from",
    "if",
    "in",
    "is",
    "not",
    "of",
    "on",
    "or",
    "the",
    "to",
    "we",
    "with",
    "such",
    "using",
    "whether",
    "into",
}

# if a phrase starts with these, treat as verb-led job-duty line (heuristic for filtering).
verbLeadTokens = {
    "build",
    "design",
    "assess",
    "use",
    "work",
    "develop",
    "create",
    "implement",
    "perform",
    "integrate",
    "ensure",
    "evaluate",
    "collaborate",
    "participate",
}

# generic tokens: never promote as stack/signal terms when building domain signals from boosts.
stackTokenBlocklist = {
    "to",
    "full",
    "engineering",
    "development",
    "work",
    "sales",
    "business",
    "performance",
    "account",
    "opportunities",
    "clients",
    "relationships",
    "leadership",
    "ownership",
    "company",
    "benefits",
    "experience",
    "technical",
    "customer",
    "using",
}

# short acronyms allowed as stack tokens despite length (sql, api, aws, etc.).
stackAllowShortTokens = {
    "ai",
    "ml",
    "sql",
    "api",
    "aws",
    "gcp",
    "gke",
    "llm",
    "rag",
    "cx",
    "ivr",
    "fcr",
    "csat",
    "wfo",
    "ccaas",
    "wxcc",
}

# concrete tech names for stack detection in jd "stack" style sections.
concreteStackTerms = {
    "react", "next.js", "nextjs", "react-native", "react native", "typescript", "javascript", "node", "node.js",
    "c++", "python", "java", "rust", "php", "nestjs", "django", "flask", "fastapi",     "graphql", "rest", "restful",
    "sql", "postgres", "postgresql", "mysql", "mongodb", "redis", "databricks", "kafka", "nifi",
    "opensearch", "tableau", "power bi", "salesforce", "posthog", "aws", "gcp", "azure", "docker", "kubernetes",
    "gke", "rag", "llm", "mlops", "tensorflow", "pytorch", "pyspark", "scikit-learn", "transformers", "langchain", "langgraph",
    "express",
    "webex", "calabrio", "dialogflow", "ci/cd", "linux", "vue.js", "angular", "html", "css", "gpu", "cuda",
    "javascript", "nodejs",
    "ruby", "rails", "tailwind", "claude", "ios", "android",
}

# softer capability words: stack-adjacent but not a named product (workflow, compliance, etc.).
# omit integration / support / documentation / efficiency / operations: most JDs; operations over-boosted with body + capabilityStack.
roleCapabilityStackTerms = {
    "implementation", "delivery",
    "billing", "security", "kpis", "compliance",
}

# tokens to skip when mining org/employer name chunks from titles (too generic).
orgTokenStopwords = {
    "the",
    "and",
    "for",
    "with",
    "inc",
    "llc",
    "corp",
    "company",
    "remote",
    "today",
    "apply",
    "job",
    "jobs",
    "manager",
    "engineer",
    "developer",
    "position",
    "opening",
    "career",
    "opportunity",
    "role",
}



# substrings: any line containing these is treated as non-skill boilerplate for suppression.
wrapperSuppressLineSubstrings = {
    "apply now",
    "apply today",
    "talk to",
    "for free",
    "message and data rates",
    "we never post fake jobs",
    "equal opportunity",
    "we are looking for",
    "ideal candidate",
    "join our team",
    "opportunity to",
    "hiring for",
    "submit your resume",
    "send us your resume",
    "all qualified applicants",
    "women and minorities are encouraged",
    "equal employment opportunity",
    "background records check",
    "public trust clearance",
    "us citizenship",
    "perm resident alien",
    "privacy policy",
    "employment eligibility",
    "opt out",
    "message and data rates may apply",
    "must be able to pass",
    "drug screening",
    "drug test",
    "criminal background check",
    "work authorization required",
    "subject to background",
    "equal opportunity employer",
    "please include",
    "relevant title",
    "job title in subject",
    "if interested send",
    "paid time off",
    "holiday pay",
    "sick leave",
    "medical dental vision",
    "next steps",
    "dream job",
    "recruiter network",
    "who are our recruiters",
    "by clicking apply today you agree",
    "carriers are not liable",
    "cease communicating",
    "not sure if you meet every requirement",
    "we value your",
    "we value our communities",
    "continental united states of america",
    "integral part of the continued growth",
    "our mission is clear",
    "improve their lives and livelihood",
    "additional benefits and pay",
    "pay range is the lowest",
    "competitive compensation package",
    "women and minorities are encouraged to apply",
    "equal employment opportunity company",
    "drug free work place",
    "company paid",
    "business casual dress code",
    "community outreach opportunities",
    "employee recognition programs",
    "holiday bonus",
    "hybrid work",
    "tuition reimbursement",
    "healthcare benefits",
    "401k",
    "vacation time",
    "sick time",
    "team building activities",
    "friends and family nights",
    "active lifestyle",
    "agency including",
    "agency submits",
    "any candidate for whom",
    "deemed referred",
    "fax",
    "mailing address",
    "placement resulting from",
    "property of the company",
    "resume database",
    "unsolicited resume",
    "unsolicited resumes",
    "will not pay a fee",
    "but enough about us",
    "competitive salary",
    "employer-paid",
    "one last thing to ask yourself",
    "the base salary for this position is",
    "unlimited pto",
    "we are looking to build something big",
    "we have an ever-evolving list of values",
    "we have created a world where",
    "equal employment opportunities",
    "without regard to race",
    "qualified candidates should send a resume",
    "life at lennar",
    "follow us on social media",
    "linkedin",
    "physical & office site presence requirements",
    "physical & office site presence",
    "weekly team nights",
    "paid traveling opportunities",
    "networking with business owners",
    "supportive and encouraging work environment",
    "student-mentality",
    "student mentality",
    "base draw commission bonuses",
    "gas allowance",
    "discounted gym memberships",
    "travel opportunities",
    "health benefits",
    "performance based role",
    "applications without this will not be reviewed",
    "check us out: instagram",
    "youtube:",
    "tiktok:",
    "website:",
    "to apply, email",
    "no resume needed",
    "click here",
    "employment list",
    "temporary position",
    "inclusive and supportive workforce",
    "minimum qualifications",
    "license or certificate",
    "check out our career page",
    "go to careers",
    "401(k)",
    "life insurance",
    "short term",
    "long term disability",
    "employee referral bonus",
    "advancement opportunities",
}

# when merging overlapping terms: if generic token overlaps a longer phrase, prefer these exact phrases.
phraseOverlapExactPrefer = {
    "api": {"restful apis", "api integration", "third-party apis"},
    "ai": {"generative ai", "ai agents", "llm-based solutions"},
    "management": {"project management", "account management", "hospitality management"},
    "customer": {"customer service", "customer outcomes"},
    "service": {"customer service", "professional services"},
}

# weak adjectives at phrase edges; signal fluff not substance.
lowSignalModifierTokens = {
    "strong",
    "clear",
    "comprehensive",
    "another",
    "top",
    "green",
    "new",
    "high",
    "great",
}

# tokens that suggest a tooling list (used to allow tool-heavy short phrases).
toolListFragmentTokens = {
    "python",
    "java",
    "javascript",
    "typescript",
    "node",
    "node.js",
    "django",
    "fastapi",
    "flask",
    "react",
    "next.js",
    "nestjs",
    "aws",
    "gcp",
    "azure",
    "docker",
    "kubernetes",
    "sql",
    "mysql",
    "postgresql",
    "graphql",
    "alteryx",
    "tableau",
    "power bi",
}

# resume-speak filler: drop single-token hits from weak sources.
fillerFunctionTokens = {
    "during",
    "functions",
    "environment",
    "degree",
    "must",
    "perform",
    "across",
    "analyses",
    "analysis",
    "eg",
    "e.g",
}


# pronouns in ngrams: skip (not skill terms).
phrasePronounTokens = {
    "you",
    "your",
    "yours",
    "our",
    "ours",
    "their",
    "theirs",
    "we",
    "us",
}


# reject two-word title fragments ending in these unless phrase is in known list.
titleFragmentBlacklistTailTokens = {"associate", "assistant"}

# org/location nouns: bad tail on "x manager y" fragments.
orgLocationPhraseTokens = {
    "outlet",
    "outlets",
    "school",
    "university",
    "college",
    "hospital",
    "clinic",
    "center",
    "centre",
    "district",
    "campus",
    "county",
    "city",
    "state",
    "region",
    "branch",
    "location",
    "office",
}

# weak trailing tokens in extracted phrases (job-post narrative glue).
phraseGlueTrailTokens = {
    "will",
    "would",
    "could",
    "should",
    "ability",
    "teams",
    "team",
    "group",
    "groups",
}

# narrative/job-meta words at end of ing-phrase (weak skill signal).
narrativeTrailTokens = {
    "business",
    "vertical",
    "role",
    "position",
    "candidate",
    "opportunity",
    "title",
}

# line looks like a url or document link; skip keyword extraction on that line.
urlLinePatterns = (
    r"https?://",
    r"\bwww\.",
    r"\.(gov|mil|pdf|docx?|pptx?|xlsx?)\b",
    r"\b[A-Za-z0-9.-]+\.(gov|mil|pdf|org|com)\b",
)

# compliance/disclaimer footer lines (dol, eeo, posters).
complianceFooterSubstrings = {
    "know your rights",
    "pay transparency",
    "ofccp",
    "equal employment opportunity",
    "eeo",
    "dol.gov",
    "department of labor",
    "poster",
    "supplement",
    "download",
    "pdf",
    "poster notice",
}

# multiplier applied when scoring text under downweighted section headers.
downweightFactor = 0.35
