"""add_daily_tailor_cap

Revision ID: 3370e73b321a
Revises: 623682c7611e
Create Date: 2026-06-03 00:41:50.323283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3370e73b321a'
down_revision: Union[str, Sequence[str], None] = '623682c7611e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_tailor_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('daily_tailor_reset_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_tailor_reset_date')
        batch_op.drop_column('daily_tailor_count')

    # ### end Alembic commands ###
